apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
  namespace: argocd
spec:
  selector:
    appName: {{ .Values.component }}
    projectName: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}



#  ExpenseApp123----DB_PASS
#expense----DB_USER
